version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # glib is only used on linux and I'm only building for windows
      - dependency-name: "glib"
        versions: ["*"]
